### vars
@livehost = https://auth.knight.works/api/v1
@port = 3001
@localhost = http://localhost:{{port}}/api/v1
@contentType = application/json

### verify
GET {{livehost}}/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImVtYWlsIjoiam9yZGFuKzE4QGtuaWdodC53b3JrcyIsInNpdGUiOiJjbG91ZC5rbmlnaHQud29ya3MiLCJpYXQiOjE1NzI3MzAxMzUsImV4cCI6MTU3MjgxNjUzNX0.2E8c1ZUwyMvFnRHljSK4EZO0rVVuRaAlbE0-lF_Yv_w


###

###
POST {{livehost}}/register
# POST {{localhost}}/register
content-type: {{contentType}}

{
    "email": "jordan+20@knight.works",
    "password": "test",
    "site": "admin.knight.works"
}
###
GET {{localhost}}/users
content-type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb3JkYW4rMTBAa25pZ2h0LndvcmtzIiwic2l0ZSI6ImxvY2FsaG9zdCIsImlhdCI6MTU3ODAzMDc4NiwiZXhwIjoxNTc4MTE3MTg2fQ.WAfj5krPMoJ3rfAp6ByxPC7iJ7mhH6zNvyglE6zQw8U

###
{
    "email": "jordan+63@knight.works",
    "password": "test",
    "site": "admin.knight.works"
}
###
//GET /users
GET {{localhost}}/users
####

POST {{localhost}}/login
content-type: {{contentType}}

{
    "email": "jordan+14@knight.works",
    "password": "test"
}

###
POST {{livehost}}/login
content-type: application/json

{
    "email": "jordan+10@knight.works",
    "password": "test"
}

###
### Refresh
POST {{localhost}}/refresh
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEJJQVVLRmJCakk2dGxHQVFxVTNHNnViQUNLS2tTZWkyUGNxRlZESE1acmU2VEJtekUwOGpTIiwiaWF0IjoxNTcyNzIzMzM2fQ.H94OYXkcQKEsaYP4m549g47ch5VfJA_1v2RtU-_JsMs"
}

### Refresh
POST {{localhost}}/logout
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEJJQVVLRmJCakk2dGxHQVFxVTNHNnViQUNLS2tTZWkyUGNxRlZESE1acmU2VEJtekUwOGpTIiwiaWF0IjoxNTcyNzIzMzM2fQ.H94OYXkcQKEsaYP4m549g47ch5VfJA_1v2RtU-_JsMs"
}
###